TuringLang/AbstractMCMC.jl

.gitignore, Project.toml, README.md, src/AbstractMCMC.jl
This consolidates the MCMC interface and it's abstract types from Turing and the abstract types from MCMCChains into one lightweight package.
=> Migrate code from Turing/MCMCChains

src/AbstractMCMC.jl
It feels wrong to define and export `Chains` in this package even though the `Chains` struct is defined in MCMCChains. Since the `Chains` function definition in this package only throws an error, IMO it should be removed.
=> Remove Chains

src/AbstractMCMC.jl
The PR makes it such that `bundle_samples` will default to just returning the vector of `AbstractTransition` object when no overload has been defined, so you could theoretically get around having a heavy `MCMCChains` constructor by simply not defining `bundle_samples`.
=> Return a vector of samples instead of an error

src/AbstractMCMC.jl
Users can now pass in a keyword argument to `sample` to define the type of the chain they want to receive after sampling. It's the responsibility of package developers to support chain construction for different types. An example of usage might be
```julia
chain1 = sample(model, sampler, 1000; chain_type = NamedTuple)
chain2 = sample(model, sampler, 1000; chain_type = MCMCChains.Chains)
chain3 = sample(model, sampler, 1000; chain_type = Array)
```
If no keyword is specified, this defaults to whatever a package developer sets as the default constructor `bundle_samples`, or it simply returns the vector of `AbstractTransition` if the package developer has not created a catch-all overload of `bundle_samples`.
=> Allow dispatch on chain type

src/AbstractMCMC.jl, test/interface.jl, test/runtests.jl
I undid #6 because I missed some comments. I've addressed them here by pulling out some static type constraints and allowing for a single default `bundle_samples` method instead of two.
=> Allow dispatch on chain type (take two)

src/AbstractMCMC.jl, test/interface.jl, test/runtests.jl
I've thought a bit more about `transition_type`, and how to improve on what I mentioned in https://github.com/TuringLang/AbstractMCMC.jl/pull/9#discussion_r370753197.
In this PR I propose the following changes:
- Remove `transition_type` and instead just obtain the first transition
- Pass the initial transition to `transitions_init`, whose default implementation just creates a vector for `N` transitions of the type of the initial transition
- Add a function `transitions_save!` to which (among others) the transitions container, the current iteration, and the current transition is passed; the default implementation for vector-type containers just saves the current transition in the container
- Remove `AbstractTransition`
- Do not export anything
The main advantages with this approach are:
- …
=> Change handling of transitions

src/AbstractMCMC.jl
IMO we should not implement these methods since we do not provide a useful default implementation and stuff like `Base.hcat(c::AbstractChains...) = cat(c...; dims=2)` will invalidate the default definition of `hcat()` in Base (which might be related to https://github.com/TuringLang/MCMCChains.jl/issues/171).
=> Do not implement methods from Base

Project.toml, src/AbstractMCMC.jl, test/runtests.jl
Allows the use of `steps!`, which returns an iterator that continuously draws samples. Currently it's pretty bare bones, but I'm open to suggestions on what other functionality that could be included.
Usage:
```julia
for (total, transition) in enumerate(AbstractMCMC.steps!(MyModel(), MySampler()))
println(transition)
if total >= 1000
break
end
end
```
=> Add iterator interface

Project.toml, src/AbstractMCMC.jl, test/runtests.jl
This PR removes `AbstractCallback` and instead allows the user to provide a custom callback function. Moreover, progress logging is separated from callback handling and uses ProgressLogging instead of ProgressMeter.
ProgressLogging uses Julia's logging system to create, update, and display progress bars. It integrates nicely with Juno and can also be used in the terminal with TerminalLoggers. Among others, it is used by JuliaDiffEq and Flux for displaying progress bars. The current implementation does not make use of the updated functionality (e.g., nested progress bars) and API in ProgressLogging 0.1.1 since it is not fully supported yet by, e.g., TerminalLoggers.
=> Use ProgressLogging instead of ProgressMeter

Project.toml, src/AbstractMCMC.jl
When I updated Turing VI to use `@ifwithprogresslogger` as well I noticed a stupid bug which limits the reuse of the macro in other packages (currently it only works correctly when used inside of AbstractMCMC).
=> Fix module of progress logger

src/AbstractMCMC.jl
Although ConsoleProgressMonitor is considered "more or less dead", it seems to work a bit better on Windows (see https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/450#issuecomment-596313957).
=> Use ConsoleProgressMonitor on Windows

src/sample.jl
This PR is a proposal for simplifying the callback interface.
The removed arguments are known before sampling and hence, if needed, the callback can be defined as closure over these arguments. The RNG, the model, and the sampler are kept since they are not known (or rather their copies have not been created yet) before parallel sampling. Alternatively, these arguments could be included only in the callback interface for parallel sampling.
=> Simplify callback interface

Project.toml, src/interface.jl
We really shouldn't have a default implementation of the full argument `step!` function in this package.
=> Do not implement `step!` function

src/sample.jl, test/runtests.jl
On Slack it was suggested that it might be helpful if users are presented with a warning if they (probably unintentionally) specify more chains than number of samples in parallel sampling.
In general, I think the problem indicates that maybe both the number of samples and number chains should be keyword arguments (they are not used for dispatching and I can hardly imagine any downstream code would want to dispatch on them). We could present the warning for now and keep this in mind/include it in the next breaking release.
=> Check if the number of chains is greater than the number of samples per chain

.travis.yml, Project.toml, src/AbstractMCMC.jl, src/interface.jl, src/sample.jl, test/interface.jl, test/runtests.jl
This PR addresses the problem with `transition_save!` for stochastic control flow mentioned in https://github.com/TuringLang/DynamicPPL.jl/pull/105#issue-413520535. It changes the default implementations for writing and appending to a container of transitions from `setindex!` and `push!` to `BangBang.setindex!!` and `BangBang.push!!` which widen the container or return a new immutable instance if needed. For consistency with these default implementations and to indicate that one has to return the (potentially new) container, I renamed `transitions_save!` to ``save!!` (and `transitions_init` to just `transitions`).
I'm wondering, should we start with merging such breaking changes to a dev branch first? I assume that, e.g., solving or addressing …
=> Use BangBang to widen containers if needed

src/interface.jl
While testing stochastic control flow in Turing and DynamicPPL, I ran into an issue where `BangBang.setindex!!` tries to copy all of the old vector of transitions. Some of the elements of this vector would be undefined so it would throw and undefined reference error. This PR uses `BangBang.push!!` and `sizehint!` instead.
=> Fix undefined reference error when type widening

Project.toml, src/AbstractMCMC.jl, src/transducer.jl, test/runtests.jl, test/transducer.jl
I don't know if this PR should ever be merged, it's mainly me playing around with and learning about transducers. I assume transducers could be useful in AbstractMCMC since it's easy to combine and nest them with good performance (see, e.g., https://github.com/JuliaLang/julia/pull/33526). Some rudimentary progress logging can be achieved with `Transducers.withprogress`. Parallel reductions (multicore or multithreaded) can be achieved easily, and it's also easy to only save every nth element, drop samples, or iterate until some criterion is met.
Currently the implementation feels a bit weird since the transducer is mutated, ideally stepping would not mutate the model or the sampler (not sure how to deal with the RNG) (see https://github.com/TuringLang/AbstractMCMC.jl/issues/31).
=> Add a `Sample` transducer

src/interface.jl, src/sample.jl, test/sample.jl
This PR tries to address https://github.com/TuringLang/AbstractMCMC.jl/issues/44 by adding a method for (hopefully) concretizing arrays of type `Vector{Any}` and a `chainsstack(x::AbstractVector)` that falls back to `reduce(chainscat, x)` or `x`, depending on whether `eltype(x) <: AbstractChains` or not.
=> Add `chainsstack`

src/interface.jl, test/sample.jl, test/utils.jl
While updating AdvancedMH I noticed that we define a bunch of `bundle_samples` implementations there. I was wondering if we could generalize that in a way such that we don't have to repeat it in every package. In particular, it seems a bit strange to reimplement it in every package for `Vector{NamedTuple}` even though the only difference is how the samples are converted to a `NamedTuple`. But one could, e.g., also have a generic version for MCMCChains.Chains in MCMCChains with the basic structure + an interface for other packages to convert the samples, retrieve the names, the log-evidence + save the state, sampler, and model in a standardized way (and not different in every package).
This PR contains a very generic implementation for any desired vector-valued output.
=> Provide generic implementation of `bundle_samples` for `Vector{T}`

Project.toml, src/stepper.jl, test/stepper.jl
This really seems like a bug to me, but maybe I'm just brainfarting at 1am (it has happened before).
=> Fixed missing semi-colon for kwargs in `steps`

Project.toml, README.md, src/sample.jl, test/sample.jl
This PR moves the `setprogress!` logic from Turing upstream. IMO it belongs here since it allows to tune the default keyword arguments. The change is non-breaking since the default is not changed and it can be specified in the `sample`/`mcmcsample` calls as before.
Some additional background:
The main reason for `mcmcsample` is that Turing wants to use different default keyword arguments for `sample` but I guess it might be better to allow to set or define the keyword arguments instead. E.g., by adding an additional `default_chain_type(model, sampler) = Any` function that could be implemented as `default_chain_type(::Model, ::Sampler{<:InferenceAlgorithm}) = Chain` in Turing.
=> Allow to enable and disable progress logging globally

Project.toml, src/sample.jl
This PR limits the update frequency of the progress bars to one update per 0.5% progress. This is the default value of [`@progress`](https://junolab.org/ProgressLogging.jl/dev/#ProgressLogging.@progress-Tuple). Progress logging is quite slow and therefore this should speed up sampling.
=> Limit update frequency of progress bars

Project.toml, src/logging.jl, test/sample.jl
It seems TerminalLoggers can be used for rendering progress bars on Windows with recent versions of Julia: https://c42f.github.io/TerminalLoggers.jl/dev/#Progress-bars-1
I don't have access to a computer with Windows, so it would be good if someone could confirm that it works fine before merging the PR.
=> Use TerminalLoggers also on Windows for Julia >= 1.5.3

.github/workflows/IntegrationTest.yml, README.md
This PR adds downstream tests to avoid any unintentional breakage of the interface. More packages (in particular Turing) could be added but to avoid excessive test times it would be helpful if these repos would support running a subset of tests, such as e.g. in Bijectors (inspired by SciML) with a `GROUP` environment variable: https://github.com/TuringLang/Bijectors.jl/blob/ad6b01c4a214562ef845ab3b5a0a296b348e1ba9/test/runtests.jl#L29
=> Add integration tests

Project.toml, README.md, src/sample.jl, test/sample.jl
Following #55 , `state` and `kwargs...` are passed to the `callback` function.
=> Include `state` and `kwargs...` to `callback`

Project.toml, src/sample.jl, test/sample.jl
#56 changed the callback signature but did not update it for the convergence sampling `mcmcsample`.
=> fix callback signature in convergence mcmcsample

Project.toml, README.md, src/sample.jl, test/utils.jl
Breaking change to `isdone` signature
fixes #67
=> add `state` to isdone signature

Project.toml, README.md, src/AbstractMCMC.jl, src/metadata.jl, src/sample.jl, src/samplingstats.jl, test/sample.jl, test/utils.jl
This PR adds a `Metadata` struct that tracks the following information:
1. Start time
2. Stop time
3. Step time (time spent per step)
4. Step calls (how many times `step!` was called)
5. Allocations
It's created and passed as a keyword argument to `bundle_samples`, so it remains up to end-chain software to determine what to do (if anything) with the metadata.
=> Add Metadata struct

Project.toml, docs/src/api.md, src/AbstractMCMC.jl, src/deprecations.jl, src/sample.jl, test/sample.jl
I often run into the case where I want to get multiple chains but don't want to go through the hassle of making things threadsafe or available to each process. The common way to do this currently is something like
```julia
chains = map(x -> sample(model, spl, n), 1:10) # sample ten chains
chain = reduce(chainscat, chains)
```
Which is fine, but it is odd that we don't have a convenient way of sampling multiple chains in a basic way. 
I added `MCMCSerial` as a parallelization subtype, so you can now simply call
```julia
chain = sample(model, spl, MCMCSerial(), n, 10)
```
which will sample each subchain in turn and concatenate them. Tests are included.
I'm also open to changing the call here --  it seems to me that this should be the default behavior of something like
```julia
sample(model, …
```
=> Add MCMCSerial

.github/workflows/CompatHelper.yml, .github/workflows/TagBot.yml
I just noticed that no docs exist for tagged releases. The problem is that TagBot is not allowed to trigger other actions.
=> Build stable documentation

test/stepper.jl, test/transducer.jl
This PR fixes the test error revealed by https://github.com/TuringLang/AbstractMCMC.jl/pull/91 (hopefully): The MCMCChains error seems to be a downstream problem caused by Plots or UnicodePlots but AbstractMCMC's tests failed as well (https://github.com/TuringLang/AbstractMCMC.jl/runs/4870654544?check_suite_focus=true).
=> Fix test error

.github/workflows/CI.yml, Project.toml, src/sample.jl
One must not use `threadid` in `@threads for ....`, as discussed in https://discourse.julialang.org/t/behavior-of-threads-threads-for-loop/76042. This PR implements an alternative suggested in https://github.com/JuliaMolSim/DFTK.jl/issues/588.
Edit: Since `@spawn` was introduced in Julia 1.3, we have to drop Julia < 1.3 or add special version guards.
=> Remove use of `threadid`

.github/workflows/CI.yml, Project.toml, src/sample.jl, test/sample.jl
I noticed that in #95 I accidentally introduced a reproducibility issue for multithreaded sampling: If seeds are set for each chunk (as in the PR), then the samples will depend on the number of threads. This PR fixes the issue and reverts this change: For each chain, the RNG is set to a specific reproducible seed.
Additionally, I added the same seeds to the serial sampling (they are already used in the distributed sampling). This ensures that the samples do not depend on the chosen ensemble methods. It could be removed from the PR if not desired.
=> Ensure ensemble sampling is reproducible

Project.toml
Fixes the version number which should be 3.3.1 instead of 3.3.2: https://github.com/TuringLang/AbstractMCMC.jl/pull/97#issuecomment-1048138415
=> Fix version number

Project.toml, docs/src/api.md, src/sample.jl, src/stepper.jl, src/transducer.jl, test/sample.jl, test/stepper.jl, test/transducer.jl
This PR fixes a bug in `discard_initial`. Additionally, it adds support for `discard_initial` and `thinning` to the iterator and transducer.
Of course, it would be possible to achieve the same behaviour in the iterator/transducer by using `Iterators.drop`/`Transducers.Drop` etc. but I think support for these two keyword arguments improves the user experience since it is more consistent with `sample` and arguably simpler.
The PR also adds tests for these two keyword arguments.
=> Fix `discard_initial`, and add support for `discard_initial` and `thinning` to iterator and transducer

Project.toml, test/stepper.jl, test/transducer.jl
It seems there are still random test errors that are difficult to reproduce. It seems replacing `===` with `==` was helpful, so this PR changes it in more places (`===` was used since the initial sample of `a` is `missing` and can't be compared with `==`).
=> More stable tests

Project.toml, src/sample.jl, src/stepper.jl, src/transducer.jl, test/sample.jl, test/utils.jl
In Julia >= 1.3, actually `Random.default_rng()` is the intended (and now also properly documented: https://github.com/JuliaLang/julia/pull/44733) way to obtain the default RNG.
=> Replace `GLOBAL_RNG` with `default_rng()`

.github/workflows/IntegrationTest.yml, Project.toml, src/AbstractMCMC.jl, src/logdensityproblems.jl
This PR proposes to check if the log density actually supports the LogDensityProblems interface when constructing a LogDensityModel.
Addresses https://github.com/TuringLang/AdvancedHMC.jl/pull/301#discussion_r1056947753.
=> Check if log density supports LogDensityProblems

Project.toml, test/runtests.jl, test/sample.jl
This PR removes tests of progress logging with Atom/Juno since it holds back other test dependencies: The package is in maintenance-only mode and CompatHelper PRs are not merged anymore (see https://github.com/JunoLab/Atom.jl/pulls).
=> Do not test Atom/Juno

Project.toml, src/interface.jl, test/sample.jl
Alternative to #120 which keeps the current functionality.
@torfjelde Do you have a MWE of the ambiguity issues? Or can confirm that this PR would fix the issues you ran into?
=> Fix method ambiguity issues

docs/src/api.md
=> Update callback signature in docs

Project.toml, docs/src/api.md, src/sample.jl, test/runtests.jl, test/sample.jl
Fixes https://github.com/TuringLang/AbstractMCMC.jl/issues/125
=> Use _init_parmas for MCMCThreads and MCMCDistributed too

Project.toml
=> Breaking release: v5.0.0

Project.toml, src/AbstractMCMC.jl, test/logdensityproblems.jl
If a user creates their own AbstractMCMC sampler and passes it something that obeys the LogDensityProblems.jl interface, AbstractMCMC quietly wraps it in a `LogDensityModel` type which doesn't obey the same interface, which can be mildly confusing. (Well, it did catch me out, so there may be other new users out there too who bumped into it too :))
As this is a conscious decision (cf. https://github.com/TuringLang/AbstractMCMC.jl/pull/110#discussion_r1043893301) this PR makes it such that if somebody tries to call LogDensityProblems.jl methods on a LogDensityModel, they get a friendly nudge in the right direction.
MWE:
```julia
julia> using LogDensityProblems
julia> using AbstractMCMC: LogDensityModel
julia> struct MyModel end
julia> # In practice one would define more methods, but this is …
```
=> Add error hint for MethodErrors on LogDensityModel

src/sample.jl
My take-away from https://github.com/JuliaLang/julia/issues/42899 is that we should use `copy` instead of `deepcopy` for RNGs. More generally, based on https://github.com/JuliaLang/julia/issues/42899#issuecomment-1058487002 we might also want to use `copy` for models and samplers (possibly requires defining `copy` in a few downstream packages).
=> Use `copy` instead of `deepcopy` for RNGs

src/sample.jl
This has been bugging me way more than it should, but if you sample with 1 thread or 1 process it says `Sampling (1 threads)` or `Sampling (1 processes)`.
This fixes it.
-----
(It bugs me much less than this, though, which I get to see every time I commute into the office:)
=> Fix pluralisation in progress message

Project.toml, src/sample.jl
Closes #153 
If there were 6 threads and 9 chains, the previous code (https://github.com/TuringLang/AbstractMCMC.jl/blob/5a3b155ed0b8b7e97810005a22e013b8b4da2bb2/src/sample.jl#L441-L445) would generate the following `chainidxs` for each thread
```
1:2
3:4
5:6
7:8
9:10
11:10
```
Somewhere later on (probably in the fifth thread with `chainidxs = 9:10`) this causes indexing errors as we only have a vector of size 9.
This PR changes it such that for the same inputs (6 threads and 9 chains) it generates the following `chainidxs`
```
1:2
3:4
5:6
7:7
8:8
9:9
```
The error in #153 is fixed
```julia
julia> samples = [sample_chains(chain_count) for chain_count in 1:30]
30-element Vector{Chains{Float64, AxisArrays.AxisArray{Float64, 3, Array{Float64, 3}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, …
```
=> Fix indexing for chains in different threads

Project.toml, src/sample.jl
cf. https://github.com/TuringLang/Turing.jl/issues/2557
`check_initial_...` is only used when sampling multiple chains (it doesn't check the actual number of parameters in the model because AbstractMCMC has no way of knowing this), so the old error message was arguably misleading.
=> Improve error message when initial_params / initial_state has wrong length

Project.toml, src/AbstractMCMC.jl
The error hint for `MethodError` (see https://github.com/TuringLang/AbstractMCMC.jl/pull/146) is indiscriminate in that it catches _any_ `MethodError`. We can't do much about that, but we can try to restrict it to MethodErrors which only involve one of the arguments being a `LogDensityModel`.
https://github.com/TuringLang/AbstractMCMC.jl/blob/ececa17d5c354aa3279e7ce970ac768751c22fcf/src/AbstractMCMC.jl#L123-L135
Unfortunately,  `Base.parentmodule` is not defined for _callable structs_, so if you called a callable struct with the wrong arguments _and_ you happened to have AbstractMCMC in your environment, this error hint would try to take over and would itself error. I discovered this when calling `(::DynamicPPL.Model)(args...)` with the wrong combination of arguments.
This PR fixes it by …
=> Prevent spurious error hints

Project.toml, docs/src/api.md, src/AbstractMCMC.jl, src/logging.jl, src/sample.jl, test/sample.jl
This PR introduces more informative progress bars with `MCMCThreads` which can be configured by the user (see options below).
In today's meeting it was generally agreed that having one progress bar per chain was more informative / useful, and that an upper bound could be placed to disable that by default if there were more than `MAX_CHAINS_PROGRESS` chains.
This PR sets `MAX_CHAINS_PROGRESS = 10`. The user can override the default on a case-by-case basis using the `Symbol` versions of `progress`, or can globally set the threshold using `setmaxchainsprogress!(N)`.
For `MCMCSerial` no change is made (it already had one progress bar per chain).
For `MCMCDistributed`, `progress = :overall` is implemented (`progress = true` is a synonym for that) but `progress = :perchain` isn't, not for any …
=> Progress bars when sampling multiple chains

Project.toml, src/logging.jl, src/sample.jl
make it a global const + use `get_n_updates` where necessary to resolve this dynamically
=> Avoid hardcoding 200 updates per chain

Project.toml, docs/src/api.md, src/sample.jl, test/sample.jl
Callbacks in general have no knowledge of which chain is being sampled, meaning that there is no way to differentiate callbacks being called from different chains:
https://github.com/TuringLang/AbstractMCMC.jl/blob/33fdad814e999bdccd0b73ebf1195434da6a17c8/src/sample.jl#L235-L237
This PR makes the multiple-chain `sample` method pass a keyword argument, `chain_number`, to the single-chain `sample`. In turn this keyword argument is propagated to the callback so it can be accessed.
IMO the _better_ solution is to actually make it a _positional_ argument to the callback (when sampling a single chain it can either just be `1` or `missing`) but that would be a breaking change and I'm unsure if we want to do that in AbstractMCMC just for this. A keyword argument would just be a minor version …
=> Add `chain_number` keyword argument when performing multi-chain sampling
